// src/components/header/index.tsx
import Image from "next/image";
import styles from './styles.module.css';

export function Header() {
    return (
        <header className={styles.header}>
            <div>
                <a href="https://edcilo.com">
                    <Image 
                        src="/assets/edcilo-logo-clear.svg" 
                        width={100} 
                        height={32}
                        alt="edcilo" />
                </a>
            </div>

            <div className={styles.version}>
                v0.1.0
            </div>
        </header>
    )
}

// components/Header.vue
<script setup>
const url = ref('https://storage.edcilo.com/edcilo-logo-dark.svg')
</script>

<template>
<el-header class="header" height="auto">
    <el-image class="header--logo-img" :src="url" fit="contain" />
</el-header>
</template>

<style scoped>
.header {
    padding: 1rem;
    background-color: var(--el-bg-color);
    box-shadow: var(--el-box-shadow-light);
    border-bottom: 1px solid var(--el-border-color);
}

.header--logo-img {
    width: 90px;
    height: auto;
}
</style>
